version: "3.1"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql


  frontend:
    image: movieguesser
    container_name: frontend
    build: ./Frontend
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf


  backend:
    image: backend
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysql



volumes:
  mysql:
