version: "3.1"
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default

  frontend:
    image: movieguesser
    container_name: frontend
    build: ./Frontend
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  backend:
    image: backend
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - default


networks:
  default:

volumes:
  mysql:
