/**
 * webapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Usuario { 
    id?: number;
    username?: string | null;
    email?: string | null;
    contrasea?: string | null;
    imagen?: string | null;
    puntos?: number | null;
}

